---
- name: Pull Terraform files from Git, Install Terraform and AWS CLI, and Run Terraform Commands
  hosts: localhost
  become: yes # To run tasks with sudo

  tasks:
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present

    - name: Add HashiCorp repository
      shell: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

    - name: Install Terraform
      yum:
        name: terraform
        state: present

    - name: Install AWS CLI dependencies
      yum:
        name: unzip
        state: present

     - name: Ensure terraform directory exists
      file:
        path: "/home/ec2-user/terraform"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: "0755"

    - name: Download and install AWS CLI if not already installed
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
        unzip -o awscliv2.zip 
        sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
        echo 'export PATH=$PATH:/usr/local/bin/' >> ~/.bashrc
        source ~/.bashrc
      args:
        chdir: "/home/ec2-user/terraform"
