---
- name: Pull Terraform files from Git, Install Terraform and AWS CLI, and Run Terraform Commands
  hosts: localhost
  become: yes # To run tasks with sudo
  become_method: sudo
  become_user: ec2-user
  tasks:
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present

    - name: Add HashiCorp repository
      shell: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

    - name: Install Terraform
      yum:
        name: terraform
        state: present

    - name: Install AWS CLI dependencies
      yum:
        name: unzip
        state: present

    - name: Download and install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
      args:
        chdir: "/home/ec2-user/terraform"
